import random
from flask import session

ROLE_QUESTIONS = {

    # ==========================================================
    # SOFTWARE ENGINEER
    # ==========================================================
    "Software Engineer": {
        "easy": [
            ("What is the difference between an array and a linked list?",
             "Arrays allow fast index access while linked lists allow easier insertion and deletion."),
            ("What is object-oriented programming (OOP)?",
             "OOP is a programming paradigm based on objects that encapsulate data and behavior."),
            ("What is the purpose of version control systems?",
             "Version control tracks code changes and enables collaboration and rollback."),
            ("What is a variable in programming?",
             "A variable is a named storage location that holds a value which can change during execution."),
            ("What is the difference between a compiler and an interpreter?",
             "A compiler translates the entire program at once while an interpreter executes it line by line."),
            ("What is a function or method?",
             "A function is a reusable block of code that performs a specific task."),
            ("What is recursion?",
             "Recursion is when a function calls itself to solve smaller instances of a problem."),
            ("What is the difference between a stack and a queue?",
             "A stack follows LIFO while a queue follows FIFO order."),
            ("What is an algorithm?",
             "An algorithm is a step-by-step procedure to solve a problem or complete a task."),
            ("What is the difference between '==' and '===' in JavaScript?",
             "'==' compares values with type coercion while '===' compares both value and type strictly."),
            ("What is a class in OOP?",
             "A class is a blueprint for creating objects that share common attributes and methods."),
            ("What is inheritance in OOP?",
             "Inheritance allows a class to acquire properties and methods from another class."),
            ("What is a data type?",
             "A data type defines the kind of value a variable can hold such as integer, string, or boolean."),
            ("What is debugging?",
             "Debugging is the process of finding and fixing errors in code."),
            ("What is a loop in programming?",
             "A loop repeats a block of code while a condition is true."),
        ],
        "medium": [
            ("What is multithreading and how does it improve performance?",
             "Multithreading runs multiple tasks concurrently to improve performance."),
            ("Explain the difference between REST and SOAP APIs.",
             "REST is lightweight and uses HTTP/JSON while SOAP is protocol-based and uses XML."),
            ("What is normalization in databases?",
             "Normalization reduces data redundancy and improves database integrity."),
            ("Write a function to check if a string is a palindrome.",
             "def is_palindrome(s):\n    return s == s[::-1]"),
            ("What is Big O notation?",
             "Big O notation describes the time or space complexity of an algorithm in terms of input size."),
            ("What is the difference between SQL and NoSQL databases?",
             "SQL databases are relational and structured while NoSQL databases are flexible and schema-less."),
            ("What is polymorphism in OOP?",
             "Polymorphism allows different classes to be treated as the same type through a common interface."),
            ("What is a design pattern? Name one example.",
             "A design pattern is a reusable solution to a common problem. Example: Singleton ensures only one instance."),
            ("What is the MVC architecture?",
             "MVC separates an application into Model, View, and Controller to organize code structure."),
            ("What is encapsulation?",
             "Encapsulation hides internal object details and exposes only necessary interfaces."),
            ("What is the difference between synchronous and asynchronous programming?",
             "Synchronous code runs in sequence while asynchronous code runs tasks without blocking execution."),
            ("What is a hash map?",
             "A hash map stores key-value pairs and allows fast lookup using a hash function."),
            ("What is dependency injection?",
             "Dependency injection passes required dependencies into a class rather than creating them internally."),
            ("What is a binary search tree?",
             "A BST is a tree where each node's left child is smaller and right child is larger."),
            ("Explain the concept of exception handling.",
             "Exception handling catches and manages runtime errors to prevent crashes using try-catch blocks."),
            ("Write a Python function that reverses a list without using built-in reverse.",
             "def reverse_list(lst):\n    result = []\n    for i in range(len(lst)-1, -1, -1):\n        result.append(lst[i])\n    return result\nprint(reverse_list([1,2,3,4,5]))"),
        ],
        "hard": [
            ("Design a distributed caching system.",
             "Distribute cached data across multiple nodes using consistent hashing for scalability and fast access."),
            ("How would you design a fault-tolerant microservices architecture?",
             "Use redundancy, load balancing, circuit breakers, and failure recovery mechanisms."),
            ("Explain the CAP theorem with real-world examples.",
             "A distributed system can guarantee only two of consistency, availability, and partition tolerance at a time."),
            ("Implement binary search.",
             "def binary_search(arr, x):\n    l, r = 0, len(arr)-1\n    while l <= r:\n        m = (l+r)//2\n        if arr[m] == x: return m\n        l, r = (m+1, r) if arr[m] < x else (l, m-1)\n    return -1"),
            ("How would you design a URL shortening service like bit.ly?",
             "Use a hash function to generate short codes, store mappings in a database, and redirect via lookup."),
            ("What is eventual consistency and when would you use it?",
             "Eventual consistency allows temporary inconsistencies across distributed nodes that resolve over time."),
            ("Explain the SOLID principles.",
             "SOLID stands for Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion."),
            ("How would you design a rate limiter?",
             "Use a token bucket or sliding window algorithm to limit requests per user within a time window."),
            ("What is a memory leak and how do you prevent it?",
             "A memory leak occurs when allocated memory is never freed. Prevent it by releasing references and using profilers."),
            ("How do you design a system to handle millions of concurrent users?",
             "Use horizontal scaling, load balancers, caching layers, CDNs, and database sharding."),
            ("What is the difference between monolithic and microservices architecture?",
             "Monolithic apps are single deployable units while microservices split functions into independent services."),
            ("Explain garbage collection in programming languages.",
             "Garbage collection automatically reclaims memory from objects that are no longer referenced."),
            ("How would you implement a thread-safe singleton?",
             "Use double-checked locking or synchronized methods to ensure only one instance in multi-threaded environments."),
            ("What is a deadlock and how do you prevent it?",
             "Deadlock occurs when threads wait on each other indefinitely. Prevent using lock ordering or timeouts."),
            ("Design a notification system for millions of users.",
             "Use message queues, fan-out architecture, and push/pull mechanisms to deliver notifications at scale."),
            ("Write a Python class implementing a stack with push, pop, and peek methods.",
             "class Stack:\n    def __init__(self): self.items = []\n    def push(self, x): self.items.append(x)\n    def pop(self): return self.items.pop() if self.items else None\n    def peek(self): return self.items[-1] if self.items else None\ns = Stack()\ns.push(1)\ns.push(2)\nprint(s.peek())"),
        ],
    },

    # ==========================================================
    # DATA SCIENTIST
    # ==========================================================
    "Data Scientist": {
        "easy": [
            ("What is mean vs median?",
             "Mean is the average value while median is the middle value in ordered data."),
            ("What is overfitting in machine learning?",
             "Overfitting occurs when a model learns noise instead of general patterns."),
            ("What is a confusion matrix?",
             "A confusion matrix evaluates classification performance using predicted vs actual values."),
            ("What is exploratory data analysis (EDA)?",
             "EDA involves summarizing and visualizing data to understand its structure and patterns."),
            ("What is the difference between classification and regression?",
             "Classification predicts categories while regression predicts continuous numerical values."),
            ("What is data normalization?",
             "Data normalization scales feature values to a standard range to improve model training."),
            ("What is a null value in a dataset?",
             "A null value represents missing or undefined data in a dataset."),
            ("What is a histogram?",
             "A histogram displays the distribution of a numerical variable using bars."),
            ("What is the purpose of a train-test split?",
             "A train-test split separates data for model training and unbiased performance evaluation."),
            ("What is correlation in data analysis?",
             "Correlation measures the relationship strength and direction between two variables."),
            ("What is a data pipeline?",
             "A data pipeline automates the flow of data from source to storage or analysis."),
            ("What is the difference between structured and unstructured data?",
             "Structured data is organized in rows and columns while unstructured data has no fixed format."),
            ("What is variance in statistics?",
             "Variance measures how spread out data points are from the mean."),
            ("What is a scatter plot used for?",
             "A scatter plot visualizes the relationship between two continuous variables."),
            ("What is a feature in machine learning?",
             "A feature is an individual measurable input variable used to train a model."),
        ],
        "medium": [
            ("Explain cross-validation and why it is used.",
             "Cross-validation tests model performance by splitting data into multiple train-test sets."),
            ("What is the bias-variance tradeoff?",
             "It balances model simplicity (bias) and model flexibility (variance)."),
            ("Explain the difference between supervised and unsupervised learning.",
             "Supervised learning uses labeled data while unsupervised learning uses unlabeled data."),
            ("Load a CSV file using pandas.",
             "import pandas as pd\ndf = pd.read_csv('data.csv')\nprint(df.head())"),
            ("What is principal component analysis (PCA)?",
             "PCA reduces dimensionality by transforming features into uncorrelated principal components."),
            ("What is regularization and why is it used?",
             "Regularization adds a penalty to model complexity to reduce overfitting."),
            ("What is feature engineering?",
             "Feature engineering creates or transforms input variables to improve model performance."),
            ("Explain precision and recall.",
             "Precision measures correct positive predictions while recall measures how many actual positives were found."),
            ("What is gradient descent?",
             "Gradient descent minimizes a loss function by iteratively updating parameters in the direction of steepest descent."),
            ("What is the difference between bagging and boosting?",
             "Bagging trains models in parallel on subsets while boosting trains them sequentially to correct errors."),
            ("What is one-hot encoding?",
             "One-hot encoding converts categorical variables into binary columns for each category."),
            ("What is the ROC-AUC score?",
             "ROC-AUC measures model ability to distinguish between classes across all classification thresholds."),
            ("What is imputation in data preprocessing?",
             "Imputation fills missing values using strategies like mean, median, or model-based estimation."),
            ("What is a decision tree?",
             "A decision tree splits data into branches based on feature values to make predictions."),
            ("What is data augmentation?",
             "Data augmentation artificially expands training data by applying transformations to existing samples."),
            ("Write code to find and fill missing values in a pandas DataFrame.",
             "import pandas as pd\ndf = pd.DataFrame({'A': [1, None, 3], 'B': [4, 5, None]})\ndf.fillna(df.mean(), inplace=True)\nprint(df)"),
        ],
        "hard": [
            ("Design a recommendation system for an e-commerce platform.",
             "Use collaborative filtering or content-based filtering to suggest items based on user behavior."),
            ("Explain how you would handle imbalanced datasets.",
             "Handle imbalance using SMOTE resampling, class weighting, or threshold adjustment."),
            ("How would you deploy and monitor a machine learning model in production?",
             "Deploy models via APIs and monitor performance using metrics and drift detection."),
            ("Train a simple logistic regression model.",
             "from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression()\nmodel.fit(X_train, y_train)\nprint(model.score(X_test, y_test))"),
            ("What is concept drift and how do you detect it?",
             "Concept drift is when data distribution changes over time. Detect it using statistical monitoring."),
            ("How would you build a fraud detection system?",
             "Use anomaly detection, ensemble models, and real-time scoring with engineered transaction features."),
            ("What is a neural network and how does backpropagation work?",
             "A neural network learns through layers. Backpropagation adjusts weights using the chain rule of gradients."),
            ("How do you select the most important features in a dataset?",
             "Use feature importance scores, correlation analysis, LASSO regularization, or recursive feature elimination."),
            ("What is transfer learning?",
             "Transfer learning reuses a pretrained model's knowledge to improve performance on a new related task."),
            ("How do you evaluate a clustering algorithm?",
             "Use silhouette score, Davies-Bouldin index, or visual inspection to evaluate cluster quality."),
            ("What is the difference between LSTM and GRU networks?",
             "LSTM uses three gates for memory control while GRU uses two gates making it simpler and faster."),
            ("How would you handle high-dimensional data?",
             "Use dimensionality reduction techniques like PCA, autoencoders, or feature selection methods."),
            ("Explain the difference between generative and discriminative models.",
             "Generative models learn data distributions while discriminative models learn decision boundaries."),
            ("How do you ensure fairness and reduce bias in ML models?",
             "Audit training data, apply fairness metrics, use bias mitigation algorithms, and test across demographic groups."),
            ("What is the architecture of a random forest model?",
             "Random forest builds many decision trees on random subsets and combines their predictions by majority vote."),
            ("Write code to plot a confusion matrix using sklearn and matplotlib.",
             "from sklearn.metrics import confusion_matrix\nimport matplotlib.pyplot as plt\nimport seaborn as sns\ncm = confusion_matrix(y_test, y_pred)\nsns.heatmap(cm, annot=True, fmt='d')\nplt.show()"),
        ],
    },

    # ==========================================================
    # FRONTEND DEVELOPER
    # ==========================================================
    "Frontend Developer": {
        "easy": [
            ("What is the difference between inline and block elements?",
             "Inline elements do not start a new line while block elements take full width."),
            ("What is JavaScript hoisting?",
             "Hoisting moves variable and function declarations to the top of scope during compilation."),
            ("What is responsive web design?",
             "Responsive design adapts layouts for different screen sizes."),
            ("What is the DOM?",
             "The DOM is a tree-like representation of an HTML document that JavaScript can manipulate."),
            ("What is the difference between HTML and CSS?",
             "HTML defines structure and content while CSS controls visual styling."),
            ("What is a CSS selector?",
             "A CSS selector targets HTML elements to apply styles."),
            ("What is an event listener in JavaScript?",
             "An event listener waits for user actions like clicks and runs a function in response."),
            ("What is the box model in CSS?",
             "The box model describes how margin, border, padding, and content wrap around elements."),
            ("What is Flexbox in CSS?",
             "Flexbox is a layout model that arranges items in rows or columns with flexible sizing."),
            ("What is the difference between id and class in HTML?",
             "An id is unique per page while a class can be reused on multiple elements."),
            ("What is a semantic HTML element?",
             "Semantic elements like header and article describe content meaning to browsers and developers."),
            ("What is localStorage in JavaScript?",
             "localStorage stores key-value data in the browser that persists after the page is closed."),
            ("What is the difference between var, let, and const?",
             "var is function-scoped, let is block-scoped, and const is block-scoped and immutable."),
            ("What is a media query in CSS?",
             "A media query applies styles conditionally based on screen size or device type."),
            ("What does the async attribute do on a script tag?",
             "The async attribute loads the script asynchronously without blocking HTML parsing."),
        ],
        "medium": [
            ("Explain the virtual DOM and its advantages.",
             "Virtual DOM updates only changed elements to improve rendering performance."),
            ("What is state management in frontend applications?",
             "State management controls and shares application data across components."),
            ("How does browser rendering work?",
             "The browser parses HTML/CSS, builds the DOM/CSSOM, and paints pixels on the screen."),
            ("Create a button click event in JavaScript.",
             "<button onclick='show()'>Click</button>\n<script>\nfunction show(){ alert('Hello'); }\n</script>"),
            ("What is the difference between promises and async/await?",
             "Both handle async code but async/await provides cleaner readable syntax over promise chains."),
            ("What is CSS Grid and how does it differ from Flexbox?",
             "CSS Grid is two-dimensional for layout while Flexbox is one-dimensional for alignment."),
            ("What is event bubbling in JavaScript?",
             "Event bubbling propagates events from the target element up through its parent elements."),
            ("What is a closure in JavaScript?",
             "A closure is a function that retains access to its outer scope even after that scope has returned."),
            ("What is the purpose of a bundler like webpack?",
             "A bundler combines multiple JavaScript files and assets into optimized output for the browser."),
            ("What is CORS and why does it occur?",
             "CORS is a browser security policy that blocks cross-origin requests unless the server explicitly allows them."),
            ("What is lazy loading in frontend development?",
             "Lazy loading defers loading of non-critical resources until they are needed."),
            ("Explain the concept of debouncing.",
             "Debouncing delays a function call until a set time has passed since the last invocation."),
            ("What is a single page application (SPA)?",
             "An SPA loads one HTML page and dynamically updates content without full page reloads."),
            ("What are React hooks?",
             "React hooks like useState and useEffect let functional components use state and lifecycle features."),
            ("What is the difference between session storage and local storage?",
             "Session storage clears when the tab closes while local storage persists until manually cleared."),
            ("Write a JavaScript function that debounces another function by 300ms.",
             "function debounce(fn, delay) {\n  let timer;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}\nconst log = debounce(() => console.log('typed'), 300);"),
        ],
        "hard": [
            ("How would you implement real-time updates in a frontend application?",
             "Use WebSockets or Server-Sent Events to push live data from server to client."),
            ("Explain performance optimization techniques for large React applications.",
             "Optimize using memoization, lazy loading, code splitting, and efficient re-rendering strategies."),
            ("How would you architect a scalable frontend for millions of users?",
             "Use modular design, caching, CDN distribution, and micro-frontends for scalability."),
            ("Fetch data from an API using JavaScript.",
             "fetch('https://api.example.com/data')\n  .then(res => res.json())\n  .then(data => console.log(data))\n  .catch(err => console.error(err));"),
            ("What is the critical rendering path and how do you optimize it?",
             "The critical rendering path is the steps to display content. Optimize by minimizing render-blocking resources."),
            ("How do you implement accessibility in a web application?",
             "Use semantic HTML, ARIA attributes, keyboard navigation, and sufficient color contrast."),
            ("Explain code splitting and its benefits.",
             "Code splitting breaks JavaScript into smaller chunks loaded on demand to reduce initial load time."),
            ("What is server-side rendering (SSR) and when would you use it?",
             "SSR renders pages on the server for faster initial load and better SEO."),
            ("How do you handle state in a large React application?",
             "Use Redux, Zustand, or Context API to manage shared state across many components."),
            ("What is hydration in the context of SSR?",
             "Hydration attaches JavaScript event handlers to server-rendered HTML to make it interactive."),
            ("How would you prevent XSS attacks in a frontend application?",
             "Sanitize user input, escape output, use Content Security Policy headers, and avoid innerHTML."),
            ("What is tree shaking in modern JavaScript?",
             "Tree shaking removes unused code from bundles during the build process to reduce file size."),
            ("How do you measure and improve Core Web Vitals?",
             "Measure LCP, FID, and CLS using Lighthouse and optimize images, scripts, and layout shifts."),
            ("Explain the concept of micro-frontends.",
             "Micro-frontends split a frontend app into independently deployable pieces owned by different teams."),
            ("What is a frontend caching strategy?",
             "Use service workers, HTTP cache headers, and memoization to cache assets and API responses."),
            ("Write a React functional component that fetches and displays a list of users from an API.",
             "import { useState, useEffect } from 'react';\nfunction Users() {\n  const [users, setUsers] = useState([]);\n  useEffect(() => {\n    fetch('https://jsonplaceholder.typicode.com/users')\n      .then(r => r.json()).then(setUsers);\n  }, []);\n  return <ul>{users.map(u => <li key={u.id}>{u.name}</li>)}</ul>;\n}"),
        ],
    },

    # ==========================================================
    # ML ENGINEER
    # ==========================================================
    "ML Engineer": {
        "easy": [
            ("What is model training in machine learning?",
             "Model training teaches a model to learn patterns from data by minimizing a loss function."),
            ("What is a loss function?",
             "A loss function measures how far a model's predictions are from actual values."),
            ("What is a feature in ML?",
             "A feature is an individual measurable input variable used to make predictions."),
            ("What is a label in supervised learning?",
             "A label is the target output value the model is trained to predict."),
            ("What is an epoch in model training?",
             "An epoch is one full pass through the entire training dataset during training."),
            ("What is a learning rate?",
             "A learning rate controls how much model weights are adjusted during each training step."),
            ("What is the difference between training and inference?",
             "Training updates model weights from data while inference uses a trained model to make predictions."),
            ("What is a neural network?",
             "A neural network is a series of connected layers of nodes that learn patterns from data."),
            ("What is data preprocessing?",
             "Data preprocessing cleans and transforms raw data into a format suitable for model training."),
            ("What is the purpose of an activation function?",
             "An activation function introduces non-linearity to help a network learn complex patterns."),
            ("What is a checkpoint in ML training?",
             "A checkpoint saves model weights at intervals to resume or evaluate training later."),
            ("What is batch size in training?",
             "Batch size is the number of training samples processed before model weights are updated."),
            ("What is early stopping?",
             "Early stopping halts training when validation performance stops improving to prevent overfitting."),
            ("What is a validation set?",
             "A validation set evaluates model performance during training to tune hyperparameters."),
            ("What is the difference between a model and an algorithm?",
             "An algorithm is the learning procedure while a model is the output learned from data."),
        ],
        "medium": [
            ("What is the difference between batch and stochastic gradient descent?",
             "Batch uses the full dataset per update while stochastic updates weights using one sample at a time."),
            ("What is hyperparameter tuning?",
             "Hyperparameter tuning optimizes model settings like learning rate and depth to improve performance."),
            ("What is model overfitting vs underfitting?",
             "Overfitting learns noise while underfitting fails to capture important patterns in data."),
            ("Normalize data using sklearn.",
             "from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)"),
            ("What is transfer learning and when is it useful?",
             "Transfer learning reuses a pretrained model to improve performance on a new task with less data."),
            ("Explain dropout regularization.",
             "Dropout randomly deactivates neurons during training to prevent co-adaptation and overfitting."),
            ("What is the vanishing gradient problem?",
             "Vanishing gradients cause early network layers to learn very slowly due to tiny gradient values."),
            ("What is the difference between CNN and RNN?",
             "CNNs process spatial data like images while RNNs process sequential data like text or time series."),
            ("What is an embedding in machine learning?",
             "An embedding maps discrete items like words into dense continuous vector representations."),
            ("What is cross-entropy loss?",
             "Cross-entropy loss measures the difference between predicted probability distributions and true labels."),
            ("What is data augmentation?",
             "Data augmentation artificially increases training data by applying transformations like flipping or cropping."),
            ("Explain L1 vs L2 regularization.",
             "L1 adds absolute weight penalty producing sparse models while L2 adds squared penalty shrinking all weights."),
            ("What is model quantization?",
             "Quantization reduces model size by representing weights with lower precision numbers."),
            ("What is a pipeline in machine learning?",
             "An ML pipeline chains preprocessing and modeling steps into a single reusable workflow object."),
            ("What is a confusion matrix and what does it tell you?",
             "A confusion matrix shows true and false predictions per class to evaluate classifier performance."),
            ("Write code to split a dataset into train and test sets using sklearn.",
             "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nprint(X_train.shape, X_test.shape)"),
        ],
        "hard": [
            ("How would you design an ML pipeline for production?",
             "An ML pipeline includes data ingestion, preprocessing, training, validation, deployment, and monitoring."),
            ("Explain model versioning and why it is important.",
             "Model versioning tracks changes to ensure reproducibility, rollback capability, and safe deployment."),
            ("How do you handle concept drift in deployed models?",
             "Monitor performance metrics and retrain models periodically using updated production data."),
            ("Create and train a Random Forest model.",
             "from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier()\nmodel.fit(X_train, y_train)\nprint(model.predict(X_test))"),
            ("How would you optimize a deep learning model for edge deployment?",
             "Use quantization, pruning, knowledge distillation, and model compression techniques."),
            ("What is federated learning?",
             "Federated learning trains models across decentralized devices without sharing raw data centrally."),
            ("How do you detect and mitigate bias in ML models?",
             "Audit data distributions, apply fairness constraints, and test model outcomes across sensitive groups."),
            ("Explain attention mechanisms in transformers.",
             "Attention allows models to weigh the importance of different input parts when generating each output."),
            ("How would you scale ML training to multiple GPUs?",
             "Use data parallelism to split batches across GPUs or model parallelism to split model layers."),
            ("What is ONNX and why is it useful?",
             "ONNX is an open format for ML models enabling portability between different frameworks and runtimes."),
            ("What is a GAN and how does it work?",
             "A GAN has a generator and discriminator that compete to produce realistic synthetic data."),
            ("What is the role of a feature store in ML systems?",
             "A feature store centralizes computed features for reuse across training and serving pipelines."),
            ("How do you perform A/B testing for ML models?",
             "Split traffic between model versions and measure performance differences using statistical significance."),
            ("What is the difference between online and offline learning?",
             "Online learning updates the model incrementally with new data while offline learning retrains on full batches."),
            ("How do you evaluate model fairness in a real-world deployment?",
             "Use fairness metrics like demographic parity and equalized odds across protected demographic groups."),
            ("Write code to evaluate a classification model and print precision, recall, and F1 score.",
             "from sklearn.metrics import classification_report\nprint(classification_report(y_test, y_pred))"),
        ],
    },

    # ==========================================================
    # BACKEND DEVELOPER
    # ==========================================================
    "Backend Developer": {
        "easy": [
            ("What is an API endpoint?",
             "An API endpoint is a specific URL where a client sends requests to access backend services."),
            ("What is CRUD in backend development?",
             "CRUD stands for Create, Read, Update, and Delete operations in databases."),
            ("What is a database index?",
             "A database index improves query speed by creating a quick lookup structure."),
            ("What is HTTP?",
             "HTTP is the protocol used for communication between clients and web servers."),
            ("What is the difference between GET and POST requests?",
             "GET retrieves data while POST sends data to create or update a resource on the server."),
            ("What is JSON?",
             "JSON is a lightweight text format for storing and transmitting structured data."),
            ("What is a primary key in a database?",
             "A primary key uniquely identifies each record in a database table."),
            ("What is a foreign key?",
             "A foreign key links a column in one table to the primary key in another table."),
            ("What is the difference between HTTP and HTTPS?",
             "HTTPS encrypts data transmission using SSL/TLS while HTTP sends data in plain text."),
            ("What is a session in web development?",
             "A session stores user state on the server between multiple HTTP requests."),
            ("What is caching?",
             "Caching stores frequently accessed data temporarily to reduce processing time."),
            ("What is an HTTP status code?",
             "HTTP status codes indicate the result of a request such as 200 for success or 404 for not found."),
            ("What is ORM?",
             "ORM maps database tables to programming objects for easier data manipulation without raw SQL."),
            ("What is a cookie?",
             "A cookie is a small piece of data stored in the browser to track session or user preferences."),
            ("What is a web server?",
             "A web server handles HTTP requests and serves responses to clients over the network."),
        ],
        "medium": [
            ("What is authentication vs authorization?",
             "Authentication verifies identity while authorization determines access permissions."),
            ("Explain middleware in backend frameworks.",
             "Middleware processes requests and responses between the client and server application logic."),
            ("What is connection pooling?",
             "Connection pooling reuses database connections to improve performance and reduce overhead."),
            ("Create a simple Flask API.",
             "from flask import Flask\napp = Flask(__name__)\n@app.route('/')\ndef home(): return 'Hello API'\napp.run()"),
            ("What is JWT and how is it used?",
             "JWT is a token standard used for securely transmitting authentication information between parties."),
            ("What is a RESTful API?",
             "A RESTful API follows REST principles using standard HTTP methods for stateless communication."),
            ("What is rate limiting?",
             "Rate limiting restricts the number of requests a client can make in a given time window."),
            ("What is message queuing?",
             "Message queuing decouples services by passing messages through a queue like RabbitMQ or Kafka."),
            ("What is database migration?",
             "Database migration applies schema changes incrementally using version-controlled scripts."),
            ("What is pagination in APIs?",
             "Pagination splits large result sets into pages to improve performance and usability."),
            ("Explain the concept of idempotency in APIs.",
             "An idempotent operation produces the same result whether called once or multiple times."),
            ("What is input validation and why is it important?",
             "Input validation ensures user-provided data is safe and correct before processing."),
            ("What is a webhook?",
             "A webhook is an HTTP callback that sends data to a URL when a specific event occurs."),
            ("What is the difference between SQL JOIN types?",
             "INNER JOIN returns matching rows, LEFT JOIN includes all left rows, FULL JOIN returns all rows from both."),
            ("What is a reverse proxy?",
             "A reverse proxy forwards client requests to backend servers and returns the response."),
            ("Write a simple Flask route that accepts a POST request with JSON and returns a response.",
             "from flask import Flask, request, jsonify\napp = Flask(__name__)\n@app.route('/data', methods=['POST'])\ndef data():\n    body = request.get_json()\n    return jsonify({'received': body})\napp.run()"),
        ],
        "hard": [
            ("How would you design a scalable backend system?",
             "Use load balancers, caching, database optimization, and horizontal scaling strategies."),
            ("Explain database sharding.",
             "Database sharding splits data across multiple servers to distribute load and improve scalability."),
            ("How do you handle distributed transactions?",
             "Manage distributed transactions using two-phase commit or saga patterns for consistency."),
            ("Connect to a SQLite database.",
             "import sqlite3\nconn = sqlite3.connect('test.db')\ncur = conn.cursor()\ncur.execute('SELECT sqlite_version()')\nprint(cur.fetchone())"),
            ("How would you implement a real-time chat backend?",
             "Use WebSockets for persistent connections, a message broker for routing, and Redis for fast storage."),
            ("What is the CQRS pattern?",
             "CQRS separates read and write operations into different models to optimize each independently."),
            ("How do you secure a REST API?",
             "Use HTTPS, JWT authentication, input validation, rate limiting, and proper CORS configuration."),
            ("What is event-driven architecture?",
             "Event-driven architecture uses events to trigger and communicate between decoupled services."),
            ("How would you design a multi-tenant backend system?",
             "Use separate schemas or tenant IDs to isolate data while sharing infrastructure across clients."),
            ("Explain the saga pattern for microservices.",
             "The saga pattern manages distributed transactions as a sequence of local transactions with compensating actions."),
            ("How do you optimize slow database queries?",
             "Add indexes, rewrite queries, use EXPLAIN plans, avoid N+1 problems, and consider denormalization."),
            ("How would you implement a distributed lock?",
             "Use Redis SETNX or a coordination service like ZooKeeper to manage locks across services."),
            ("How do you design an API versioning strategy?",
             "Use URL path versioning, header versioning, or query parameters to maintain backward compatibility."),
            ("What is a circuit breaker pattern?",
             "A circuit breaker stops calling a failing service temporarily to prevent cascading failures."),
            ("What is backpressure in backend systems?",
             "Backpressure signals upstream services to slow down when a downstream system is overwhelmed."),
            ("Write a Python script that queries an SQLite table and returns all rows as a list of dicts.",
             "import sqlite3\nconn = sqlite3.connect('db.sqlite3')\nconn.row_factory = sqlite3.Row\ncur = conn.cursor()\ncur.execute('SELECT * FROM users')\nrows = [dict(r) for r in cur.fetchall()]\nprint(rows)"),
        ],
    },

    # ==========================================================
    # DEVOPS ENGINEER
    # ==========================================================
    "DevOps Engineer": {
        "easy": [
            ("What is CI/CD?",
             "CI/CD automates code integration, testing, and deployment processes."),
            ("What is containerization?",
             "Containerization packages applications with dependencies to run consistently across environments."),
            ("What is version control branching?",
             "Branching allows parallel development by creating separate lines of code changes."),
            ("What is Docker?",
             "Docker is a platform that creates and runs containers for consistent application deployment."),
            ("What is the difference between a virtual machine and a container?",
             "VMs include a full OS while containers share the host OS kernel making them lighter and faster."),
            ("What is an environment variable?",
             "An environment variable stores configuration values outside code for flexible deployments."),
            ("What is SSH?",
             "SSH is a secure protocol for remotely accessing and managing servers."),
            ("What is a load balancer?",
             "A load balancer distributes incoming traffic across multiple servers for reliability."),
            ("What is logging in software systems?",
             "Logging records events and errors in an application for monitoring and debugging."),
            ("What is a Linux cron job?",
             "A cron job schedules commands or scripts to run automatically at specified times."),
            ("What does idempotent mean in a DevOps context?",
             "An idempotent operation produces the same result no matter how many times it runs."),
            ("What is a build pipeline?",
             "A build pipeline automates steps like testing and packaging code after each commit."),
            ("What is a package manager?",
             "A package manager installs and manages software libraries and dependencies."),
            ("What is a firewall in networking?",
             "A firewall filters network traffic based on rules to protect systems from unauthorized access."),
            ("What is a deployment?",
             "A deployment is the process of releasing new code to a server or environment."),
        ],
        "medium": [
            ("What is Infrastructure as Code (IaC)?",
             "IaC manages infrastructure using code and automation tools like Terraform or Ansible."),
            ("What is blue-green deployment?",
             "Blue-green deployment switches traffic between two environments to reduce downtime."),
            ("What is a reverse proxy?",
             "A reverse proxy forwards client requests to backend servers for load balancing or security."),
            ("Write a Dockerfile for a Python app.",
             "FROM python:3.9\nWORKDIR /app\nCOPY . .\nRUN pip install -r requirements.txt\nCMD [\"python\", \"app.py\"]"),
            ("What is Kubernetes and what problem does it solve?",
             "Kubernetes automates deployment, scaling, and management of containerized applications."),
            ("What is a rolling deployment?",
             "A rolling deployment gradually replaces old instances with new ones to avoid downtime."),
            ("What is observability in DevOps?",
             "Observability is the ability to understand system state through logs, metrics, and traces."),
            ("What is Ansible used for?",
             "Ansible automates configuration management, application deployment, and task execution."),
            ("What is a Helm chart?",
             "A Helm chart is a package of Kubernetes resource templates for deploying applications."),
            ("What is a service mesh?",
             "A service mesh manages service-to-service communication with load balancing and encryption."),
            ("What is the difference between horizontal and vertical scaling?",
             "Horizontal scaling adds more servers while vertical scaling increases resources on existing servers."),
            ("What is GitOps?",
             "GitOps uses Git as the single source of truth for declarative infrastructure and application deployments."),
            ("What is a container registry?",
             "A container registry stores and distributes Docker images for deployment."),
            ("What is continuous monitoring?",
             "Continuous monitoring tracks application and infrastructure health in real time after deployment."),
            ("What is a Docker Compose file?",
             "Docker Compose defines multi-container applications with their configurations in a YAML file."),
            ("Write a shell script that checks if a process is running and restarts it if not.",
             "#!/bin/bash\nPROCESS='myapp'\nif ! pgrep -x \"$PROCESS\" > /dev/null; then\n    echo \"$PROCESS not running. Starting...\"\n    ./$PROCESS &\nelse\n    echo \"$PROCESS is running.\"\nfi"),
        ],
        "hard": [
            ("How would you design a zero-downtime deployment strategy?",
             "Use rolling updates, blue-green deployments, and traffic shifting to avoid service interruption."),
            ("Explain Kubernetes architecture.",
             "Kubernetes has a control plane managing worker nodes where pods run containerized applications."),
            ("How do you implement monitoring and logging at scale?",
             "Use centralized tools like Prometheus, Grafana, and ELK stack to collect and alert on metrics."),
            ("Write a GitHub Actions CI pipeline.",
             "name: CI\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v2\n      - run: echo Build Successful"),
            ("How would you implement disaster recovery for a production system?",
             "Use multi-region deployments, regular backups, RTO/RPO planning, and automated failover."),
            ("What is chaos engineering?",
             "Chaos engineering intentionally introduces failures to test system resilience and identify weaknesses."),
            ("How do you manage secrets securely in a DevOps pipeline?",
             "Use secret managers like HashiCorp Vault or AWS Secrets Manager and avoid hardcoding secrets."),
            ("Explain the concept of immutable infrastructure.",
             "Immutable infrastructure replaces servers with new ones on each deployment instead of modifying them."),
            ("How would you design a multi-environment CI/CD pipeline?",
             "Use separate stages for dev, staging, and production with automated promotion and approval gates."),
            ("What is distributed tracing and why is it important?",
             "Distributed tracing tracks requests across services to diagnose latency and performance bottlenecks."),
            ("What is a canary deployment?",
             "A canary deployment routes a small percentage of traffic to a new version before full rollout."),
            ("How do you implement auto-scaling in Kubernetes?",
             "Use Horizontal Pod Autoscaler based on CPU or custom metrics to scale pods automatically."),
            ("How do you perform a root cause analysis after an incident?",
             "Use the five whys method, analyze logs and metrics, write a postmortem, and implement preventive actions."),
            ("What is FinOps and how does it relate to DevOps?",
             "FinOps applies financial accountability to cloud spending using DevOps practices for cost optimization."),
            ("How do you handle secrets rotation in a live system?",
             "Automate rotation using secret managers, use short-lived tokens, and ensure zero-downtime credential updates."),
            ("Write a GitHub Actions workflow that builds a Docker image and pushes it to Docker Hub.",
             "name: Docker Build\non: [push]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v2\n      - run: docker build -t myuser/myapp:latest .\n      - run: echo ${{ secrets.DOCKER_PASS }} | docker login -u myuser --password-stdin\n      - run: docker push myuser/myapp:latest"),
        ],
    },

    # ==========================================================
    # CYBER SECURITY ANALYST
    # ==========================================================
    "Cyber Security Analyst": {
        "easy": [
            ("What is phishing?",
             "Phishing is a social engineering attack that tricks users into revealing sensitive information."),
            ("What is malware?",
             "Malware is malicious software designed to damage or exploit systems."),
            ("What is encryption?",
             "Encryption converts data into a secure format to prevent unauthorized access."),
            ("What is a password policy?",
             "A password policy defines rules for creating strong passwords to protect accounts."),
            ("What is two-factor authentication?",
             "2FA adds a second verification step beyond a password to confirm user identity."),
            ("What is a VPN?",
             "A VPN creates an encrypted tunnel for secure communication over public networks."),
            ("What is social engineering?",
             "Social engineering manipulates people into revealing confidential information or performing actions."),
            ("What is a security patch?",
             "A security patch fixes known vulnerabilities in software to protect against exploits."),
            ("What is the principle of least privilege?",
             "Least privilege grants users only the minimum access needed to perform their job."),
            ("What is a DDoS attack?",
             "A DDoS attack floods a server with traffic to make it unavailable to users."),
            ("What is a brute force attack?",
             "A brute force attack tries every possible combination of credentials to gain access."),
            ("What is SSL/TLS?",
             "SSL/TLS encrypts data in transit between a browser and web server for secure communication."),
            ("What is a security audit?",
             "A security audit reviews systems and processes to identify vulnerabilities and compliance gaps."),
            ("What is antivirus software?",
             "Antivirus software detects and removes malicious programs from a system."),
            ("What is data backup and why is it important?",
             "Data backup copies data to a secondary location to recover from loss or attack."),
        ],
        "medium": [
            ("What is a firewall?",
             "A firewall filters incoming and outgoing network traffic based on security rules."),
            ("Explain two-factor authentication (2FA).",
             "2FA adds an extra verification step beyond a password to enhance account security."),
            ("What is SQL injection?",
             "SQL injection manipulates database queries through malicious input to gain unauthorized access."),
            ("Hash a password using SHA256.",
             "import hashlib\npwd = 'mypassword'\nhash_val = hashlib.sha256(pwd.encode()).hexdigest()\nprint(hash_val)"),
            ("What is a man-in-the-middle attack?",
             "A MITM attack intercepts communication between two parties to eavesdrop or alter data."),
            ("What is cross-site scripting (XSS)?",
             "XSS injects malicious scripts into web pages to execute in other users' browsers."),
            ("What is network segmentation?",
             "Network segmentation divides a network into isolated zones to limit the spread of attacks."),
            ("What is a vulnerability scan?",
             "A vulnerability scan automatically checks systems for known security weaknesses."),
            ("What is OWASP and what is its purpose?",
             "OWASP is a nonprofit that publishes security best practices and the top 10 web vulnerabilities list."),
            ("What is privilege escalation?",
             "Privilege escalation exploits vulnerabilities to gain higher-level access than authorized."),
            ("What is a honeypot in cybersecurity?",
             "A honeypot is a decoy system designed to attract and detect attackers."),
            ("What is the difference between symmetric and asymmetric encryption?",
             "Symmetric uses one key for both operations while asymmetric uses a public-private key pair."),
            ("What is intrusion detection and prevention?",
             "IDS detects suspicious activity while IPS actively blocks threats in real time."),
            ("What is PKI?",
             "PKI is a framework for managing digital certificates and public-key encryption."),
            ("What is a security token?",
             "A security token is a physical or digital device used to verify identity during authentication."),
            ("Write Python code to generate a secure random token for session management.",
             "import secrets\ntoken = secrets.token_hex(32)\nprint('Session token:', token)"),
        ],
        "hard": [
            ("How would you conduct a penetration test?",
             "A penetration test simulates attacks to identify and fix security vulnerabilities."),
            ("Explain zero-day vulnerabilities.",
             "Zero-day vulnerabilities are security flaws exploited before developers release a fix."),
            ("How do you design a secure network architecture?",
             "Use segmentation, firewalls, encryption, access controls, and defense-in-depth principles."),
            ("Implement a simple Caesar Cipher encryption.",
             "def caesar(text, shift):\n    return ''.join(chr((ord(c)-65+shift)%26+65) if c.isupper() else c for c in text)\nprint(caesar('HELLO', 3))"),
            ("How would you respond to a ransomware attack?",
             "Isolate infected systems, notify stakeholders, restore from clean backups, and investigate the breach."),
            ("What is threat modeling and how do you perform it?",
             "Threat modeling identifies assets, threat actors, attack surfaces, and mitigations using frameworks like STRIDE."),
            ("How do you implement a zero-trust security architecture?",
             "Verify every user and device on every request regardless of network location using identity-based controls."),
            ("What is SIEM and how is it used?",
             "SIEM collects and correlates security events to detect and respond to threats across the environment."),
            ("How do you secure a containerized application?",
             "Use minimal base images, scan for vulnerabilities, run as non-root, apply network policies, and manage secrets."),
            ("What is lateral movement in a cyberattack?",
             "Lateral movement is when an attacker navigates through a network after initial access to reach valuable targets."),
            ("How do you protect against insider threats?",
             "Use least privilege, monitor user behavior analytics, enforce separation of duties, and audit access logs."),
            ("What is a supply chain attack?",
             "A supply chain attack compromises software dependencies or vendors to reach the ultimate target."),
            ("How would you implement a security incident response plan?",
             "Define preparation, identification, containment, eradication, recovery, and lessons-learned phases."),
            ("What is certificate pinning?",
             "Certificate pinning associates a host with its expected certificate to prevent MITM attacks."),
            ("How do you perform digital forensics after a breach?",
             "Preserve evidence, analyze logs and disk images, reconstruct the attack timeline, and document findings."),
            ("Write Python code to scan open ports on a given host using sockets.",
             "import socket\ndef scan(host, ports):\n    for port in ports:\n        s = socket.socket()\n        s.settimeout(0.5)\n        if s.connect_ex((host, port)) == 0:\n            print(f'Port {port} is open')\n        s.close()\nscan('127.0.0.1', range(20, 1025))"),
        ],
    },

    # ==========================================================
    # CLOUD ENGINEER
    # ==========================================================
    "Cloud Engineer": {
        "easy": [
            ("What is cloud computing?",
             "Cloud computing delivers computing services over the internet on demand."),
            ("What is virtualization?",
             "Virtualization creates virtual machines to run multiple systems on one physical server."),
            ("What is SaaS?",
             "SaaS is software delivered over the internet without local installation."),
            ("What is the difference between IaaS, PaaS, and SaaS?",
             "IaaS provides infrastructure, PaaS provides a development platform, and SaaS provides ready-to-use software."),
            ("What is a cloud region?",
             "A cloud region is a geographic area containing data centers where cloud services are hosted."),
            ("What is an availability zone?",
             "An availability zone is an isolated data center within a region for fault tolerance."),
            ("What is object storage?",
             "Object storage manages data as objects with metadata, commonly used for files and backups."),
            ("What is a CDN?",
             "A CDN distributes content across global servers to reduce latency for end users."),
            ("What is serverless computing?",
             "Serverless computing runs code without managing servers and scales automatically."),
            ("What is a managed service?",
             "A managed service is a cloud offering where the provider handles infrastructure and maintenance."),
            ("What is a cloud storage bucket?",
             "A cloud storage bucket is a container for storing objects like files and images in the cloud."),
            ("What is latency in cloud systems?",
             "Latency is the time delay between a request being sent and a response being received."),
            ("What is auto-provisioning?",
             "Auto-provisioning automatically creates cloud resources based on predefined templates or triggers."),
            ("What is a cloud subscription model?",
             "Cloud subscriptions charge for usage on a pay-as-you-go or reserved capacity basis."),
            ("What is a cloud dashboard?",
             "A cloud dashboard is a web interface for managing and monitoring cloud resources."),
        ],
        "medium": [
            ("What is autoscaling in cloud systems?",
             "Autoscaling automatically adjusts computing resources based on traffic demand."),
            ("What is a Virtual Private Cloud (VPC)?",
             "A VPC is a private isolated network within a cloud provider environment."),
            ("Explain object storage vs block storage.",
             "Object storage manages data as objects while block storage stores data in fixed-size blocks."),
            ("Create an EC2 instance using boto3.",
             "import boto3\nec2 = boto3.resource('ec2')\ninstance = ec2.create_instances(\n    ImageId='ami-12345678', MinCount=1, MaxCount=1, InstanceType='t2.micro')\nprint(instance[0].id)"),
            ("What is a cloud security group?",
             "A security group is a virtual firewall controlling inbound and outbound traffic to cloud instances."),
            ("What is IAM in cloud computing?",
             "IAM manages user identities and access permissions for cloud resources."),
            ("What is a cloud snapshot?",
             "A cloud snapshot is a point-in-time copy of a disk or volume used for backup and recovery."),
            ("What is a NAT gateway?",
             "A NAT gateway allows private subnet instances to access the internet without exposing their IP."),
            ("What is CloudFormation or Terraform used for?",
             "They are IaC tools that define and provision cloud infrastructure using declarative configuration files."),
            ("What is a cloud function or Lambda?",
             "A cloud function runs event-driven code without provisioning or managing servers."),
            ("What is the shared responsibility model?",
             "The shared responsibility model divides security duties between the cloud provider and the customer."),
            ("What is a subnet in cloud networking?",
             "A subnet is a range of IP addresses within a VPC used to segment and control network traffic."),
            ("What is a cloud load balancer?",
             "A cloud load balancer distributes incoming requests across multiple instances for availability."),
            ("What is a private endpoint in cloud networking?",
             "A private endpoint allows secure access to cloud services without routing traffic over the internet."),
            ("What is elastic IP in AWS?",
             "An elastic IP is a static public IP address that can be assigned and reassigned to cloud instances."),
            ("Write Python code using boto3 to list all S3 buckets in an AWS account.",
             "import boto3\ns3 = boto3.client('s3')\nresponse = s3.list_buckets()\nfor bucket in response['Buckets']:\n    print(bucket['Name'])"),
        ],
        "hard": [
            ("How would you migrate an on-premise system to the cloud?",
             "Migration involves assessment, rehosting or refactoring, testing, and secure deployment."),
            ("Explain multi-cloud architecture.",
             "Multi-cloud architecture uses services from multiple cloud providers for flexibility and resilience."),
            ("How do you ensure high availability in cloud systems?",
             "High availability is achieved through redundancy, load balancing, and failover mechanisms."),
            ("Upload a file to S3 using boto3.",
             "import boto3\ns3 = boto3.client('s3')\ns3.upload_file('file.txt', 'mybucket', 'file.txt')\nprint('Uploaded')"),
            ("How would you design a cost-optimized cloud architecture?",
             "Use reserved instances, right-sizing, spot instances, autoscaling, and cloud cost monitoring tools."),
            ("What is cloud-native architecture?",
             "Cloud-native architecture builds scalable apps using containers, microservices, and dynamic cloud environments."),
            ("How do you implement disaster recovery in the cloud?",
             "Use multi-region replication, automated backups, RTO/RPO targets, and regular DR testing."),
            ("How would you secure a cloud environment end to end?",
             "Apply IAM least privilege, encrypt data at rest and in transit, enable logging, and use network controls."),
            ("What is FinOps and how do you implement it?",
             "FinOps aligns engineering, finance, and business teams to optimize and control cloud spending."),
            ("How would you architect a globally distributed application?",
             "Use multi-region deployments, global load balancers, data replication, and edge caching for low latency."),
            ("What is Kubernetes Federation?",
             "Kubernetes Federation manages multiple clusters across regions from a single control plane."),
            ("How do you handle data sovereignty in a multi-cloud setup?",
             "Use region-specific deployments, data residency controls, and compliance-aware storage configurations."),
            ("What is a cloud landing zone?",
             "A cloud landing zone is a pre-configured secure baseline environment for deploying workloads at scale."),
            ("What is service mesh architecture in cloud environments?",
             "A service mesh handles service-to-service communication with routing, observability, and security features."),
            ("Explain the concept of cloud-native databases.",
             "Cloud-native databases are designed for horizontal scalability, managed operations, and elastic performance."),
            ("Write a Terraform snippet to create an AWS S3 bucket with versioning enabled.",
             'resource "aws_s3_bucket" "my_bucket" {\n  bucket = "my-unique-bucket-name"\n}\nresource "aws_s3_bucket_versioning" "versioning" {\n  bucket = aws_s3_bucket.my_bucket.id\n  versioning_configuration { status = "Enabled" }\n}'),
        ],
    },
}


# =========================================================
# BEHAVIOURAL QUESTIONS
# =========================================================

BEHAVIOUR_QUESTIONS = [
    ("Describe a time you handled pressure.",
     "Candidate should explain situation, actions taken, and results achieved under pressure."),
    ("Describe a difficult decision you made.",
     "Candidate should explain reasoning process and final outcome."),
    ("How do you resolve team disagreements?",
     "Candidate should describe communication strategy and compromise approach."),
    ("How do you manage time during deadlines?",
     "Candidate should explain prioritization and task planning strategies."),
    ("Describe a failure and what you learned.",
     "Candidate should reflect on mistake and improvement steps."),
    ("Describe a time you showed leadership.",
     "Candidate should explain how they motivated or guided others and the outcome achieved."),
    ("Tell me about a time you handled conflict with a colleague.",
     "Candidate should describe the situation, communication approach, and resolution."),
    ("Describe a situation where you had to adapt to change.",
     "Candidate should explain how they adjusted to new circumstances and the results."),
    ("Give an example of when you went beyond your responsibilities.",
     "Candidate should highlight initiative taken and the positive impact created."),
    ("Tell me about a project you are most proud of.",
     "Candidate should explain their contribution, challenges faced, and the outcome."),
    ("How do you handle receiving critical feedback?",
     "Candidate should show openness to feedback and describe how they acted on it."),
    ("Describe a time you had to learn something new quickly.",
     "Candidate should explain the approach taken and how they applied the new knowledge."),
    ("Tell me about a time you disagreed with your manager.",
     "Candidate should show respectful communication and explain the resolution."),
    ("How do you prioritize tasks when everything is urgent?",
     "Candidate should describe a prioritization framework and give a concrete example."),
    ("Describe a time you worked effectively in a team.",
     "Candidate should explain their role, collaboration approach, and the team outcome."),
]


# =========================================================
# GENERATE QUESTION — no-repeat, cross-level aware
# =========================================================

def generate_question(level="easy", role="Software Engineer", qtype="technical"):

    session_key = f"asked_questions_{session.get('session_id', 'default')}"

    if session_key not in session:
        session[session_key] = []

    asked_questions = list(session[session_key])

    if qtype == "behavioural":

        available = [q for q in BEHAVIOUR_QUESTIONS if q[0] not in asked_questions]

        if not available:
            question, answer = random.choice(BEHAVIOUR_QUESTIONS)
        else:
            question, answer = random.choice(available)

    else:

        if role in ROLE_QUESTIONS:

            all_levels = ["easy", "medium", "hard"]

            # Priority 1: unseen questions at the requested difficulty level
            current_pool      = ROLE_QUESTIONS[role].get(level, [])
            available_current = [q for q in current_pool if q[0] not in asked_questions]

            # Priority 2: unseen questions at other difficulty levels
            other_pool = [
                q
                for lvl in all_levels if lvl != level
                for q in ROLE_QUESTIONS[role].get(lvl, [])
            ]
            available_other = [q for q in other_pool if q[0] not in asked_questions]

            if available_current:
                question, answer = random.choice(available_current)
            elif available_other:
                question, answer = random.choice(available_other)
            else:
                # Full pool exhausted (45 questions asked) — repeat from current level
                question, answer = random.choice(current_pool)

        else:
            return {
                "question": "Explain your technical expertise.",
                "answer": "Provide structured explanation with examples."
            }

    asked_questions.append(question)
    session[session_key] = asked_questions
    session.modified = True

    return {
        "question": question,
        "answer": answer
    }
